python_test_sources = [
  '__init__.py',
  'test_clarans.py',
  'test_common.py',
  'test_core.py',
  'test_ecosystem.py',
  'test_fast_clarans.py',
  'test_initialization.py',
  'test_regressions.py',
  'test_robustness.py',
  'test_bug_verification.py',
]

py.install_sources(
  python_test_sources,
  subdir: 'clarans/tests'
)
